[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Form submissions are handled with toast notifications
# No redirects needed

# Handle 404 errors
[[redirects]]
  from = "/*"
  to = "/404"
  status = 404

# Form handling settings
[build.processing.html]
  pretty_urls = true

# Custom headers to fix Permissions-Policy errors
[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=(), browsing-topics=(), run-ad-auction=(), join-ad-interest-group=(), private-state-token-redemption=(), private-state-token-issuance=(), private-aggregation=(), attribution-reporting=()"

# Cache Google Fonts resources
[[headers]]
  for = "https://fonts.googleapis.com/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "https://fonts.gstatic.com/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache CSS and JS
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=604800"
